// gShell is licensed under the GNU GENERAL PUBLIC LICENSE, Version 3
//
// http://www.gnu.org/licenses/gpl-3.0.en.html
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//
// gShell is based upon https://github.com/google/google-api-dotnet-client, which is licensed under the Apache 2.0
// license: https://github.com/google/google-api-dotnet-client/blob/master/LICENSE
//
// gShell is reliant upon the Google Apis. Please see the specific API pages for specific licensing information.

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a fork of google-apis-code-generator:
//       https://github.com/squid808/apis-client-generator
//
//     How neat is that? Pretty neat.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gShell.Cmdlets.Drive{

    using System;
    using System.Collections.Generic;
    using System.Management.Automation;

    using Google.Apis.Auth.OAuth2;
    using Google.Apis.Services;
    using v3 = Google.Apis.Drive.v3;
    using Data = Google.Apis.Drive.v3.Data;

    using gShell.dotNet.Utilities;
    using gShell.dotNet.Utilities.OAuth2;
    using gDrive = gShell.dotNet.Drive;

    /// <summary>
    /// A PowerShell-ready wrapper for the Drive api, as well as the resources and methods therein.
    /// </summary>
    public abstract class DriveBase : OAuth2CmdletBase
    {

        #region Properties

        /// <summary>
        /// <para type="description">The domain against which this cmdlet should run.</para>
        /// </summary>
        [Parameter(Mandatory = false)]
        [ValidateNotNullOrEmpty]
        public string Domain { get; set; }

        /// <summary>The gShell dotNet class wrapper base.</summary>
        protected static gDrive mainBase { get; set; }


        /// <summary>An instance of the About gShell dotNet resource.</summary>
        public About about { get; set; }

        /// <summary>An instance of the Changes gShell dotNet resource.</summary>
        public Changes changes { get; set; }

        /// <summary>An instance of the Channels gShell dotNet resource.</summary>
        public Channels channels { get; set; }

        /// <summary>An instance of the Comments gShell dotNet resource.</summary>
        public Comments comments { get; set; }

        /// <summary>An instance of the Files gShell dotNet resource.</summary>
        public Files files { get; set; }

        /// <summary>An instance of the Permissions gShell dotNet resource.</summary>
        public Permissions permissions { get; set; }

        /// <summary>An instance of the Replies gShell dotNet resource.</summary>
        public Replies replies { get; set; }

        /// <summary>An instance of the Revisions gShell dotNet resource.</summary>
        public Revisions revisions { get; set; }

        /// <summary>Returns the api name and version in {name}:{version} format.</summary>
        protected override string apiNameAndVersion { get { return mainBase.apiNameAndVersion; } }

        /// <summary>Gets or sets the email account the gShell Service Account should impersonate.</summary>
        protected static string gShellServiceAccount { get; set; }
        #endregion

        #region Constructors
        protected DriveBase()
        {
            mainBase = new gDrive();

            about = new About();
            changes = new Changes();
            channels = new Channels();
            comments = new Comments();
            files = new Files();
            permissions = new Permissions();
            replies = new Replies();
            revisions = new Revisions();
        }
        #endregion

        #region PowerShell Methods
        /// <summary>The gShell base implementation of the PowerShell BeginProcessing method.</summary>
        /// <remarks>If a service account needs to be identified, it should be in a child class that overrides
        /// and calls this method.</remarks>
        protected override void BeginProcessing()
        {
            var secrets = CheckForClientSecrets();
            if (secrets != null)
            {
                IEnumerable<string> scopes = EnsureScopesExist(Domain);
                Domain = mainBase.BuildService(Authenticate(scopes, secrets, Domain), gShellServiceAccount).domain;

                GWriteProgress = new gWriteProgress(WriteProgress);
            }
            else
            {
                WriteError(new ErrorRecord(null, (new Exception(
                    "Client Secrets must be set before running cmdlets. Run 'Get-Help "
                    + "Set-gShellClientSecrets -online' for more information."))));
            }
        }

        /// <summary>The gShell base implementation of the PowerShell EndProcessing method.</summary>
        /// <remarks>We need to reset the service account after every Cmdlet call to prevent the next
        /// Cmdlet from inheriting it as well.</remarks>
        protected override void EndProcessing()
        {
            gShellServiceAccount = string.Empty;
        }

        /// <summary>The gShell base implementation of the PowerShell StopProcessing method.</summary>
        /// <remarks>We need to reset the service account after every Cmdlet call to prevent the next
        /// Cmdlet from inheriting it as well.</remarks>
        protected override void StopProcessing()
        {
            gShellServiceAccount = string.Empty;
        }
        #endregion

        #region Authentication & Processing
        /// <summary>Ensure the user, domain and client secret combination work with an authenticated user.</summary>
        /// <param name="Scopes">The scopes that need to be passed through to the user authentication to Google.</param>
        /// <param name="Secrets">The client secrets.`</param>
        /// <param name="Domain">The domain for which this authentication is intended.</param>
        /// <returns>The AuthenticatedUserInfo for the authenticated user.</returns>
        protected override AuthenticatedUserInfo Authenticate(IEnumerable<string> Scopes, ClientSecrets Secrets, string Domain = null)
        {
            return mainBase.Authenticate(apiNameAndVersion, Scopes, Secrets, Domain);
        }
        #endregion

        #region Wrapped Methods



        #region About

        /// <summary>A wrapper class for the About resource.</summary>
        public class About
        {




            /// <summary>Gets information about the user, the user's Drive, and system capabilities.</summary>
            public Google.Apis.Drive.v3.Data.About Get ()
            {

                return mainBase.about.Get(gShellServiceAccount);
            }


        }
        #endregion



        #region Changes

        /// <summary>A wrapper class for the Changes resource.</summary>
        public class Changes
        {




            /// <summary>Gets the starting pageToken for listing future changes.</summary>
            public Google.Apis.Drive.v3.Data.StartPageToken GetStartPageToken ()
            {

                return mainBase.changes.GetStartPageToken(gShellServiceAccount);
            }



            /// <summary>Lists changes for a user.</summary>
            /// <param name="PageToken">The token for continuing a previous list request on the next page. This should be set to the
            /// value of 'nextPageToken' from the previous response or to the response from the getStartPageToken
            /// method.</param>
            /// <param name="properties">The optional properties for this method.</param>
            public Google.Apis.Drive.v3.Data.ChangeList List (string PageToken, gDrive.Changes.ChangesListProperties properties= null)
            {

                properties = properties ?? new gDrive.Changes.ChangesListProperties();

                return mainBase.changes.List(PageToken, properties, gShellServiceAccount);
            }



            /// <summary>Subscribes to changes for a user.</summary>
            /// <param name="ChannelBody">The body of the request.</param>
            /// <param name="PageToken">The token for continuing a previous list request on the next page. This should be set to the
            /// value of 'nextPageToken' from the previous response or to the response from the getStartPageToken
            /// method.</param>
            /// <param name="properties">The optional properties for this method.</param>
            public Google.Apis.Drive.v3.Data.Channel Watch (Google.Apis.Drive.v3.Data.Channel ChannelBody, string PageToken, gDrive.Changes.ChangesWatchProperties properties= null)
            {

                properties = properties ?? new gDrive.Changes.ChangesWatchProperties();

                return mainBase.changes.Watch(ChannelBody, PageToken, properties, gShellServiceAccount);
            }


        }
        #endregion



        #region Channels

        /// <summary>A wrapper class for the Channels resource.</summary>
        public class Channels
        {




            /// <summary>Stop watching resources through this channel</summary>
            /// <param name="ChannelBody">The body of the request.</param>
            public void Stop (Google.Apis.Drive.v3.Data.Channel ChannelBody)
            {

                mainBase.channels.Stop(ChannelBody, gShellServiceAccount);
            }


        }
        #endregion



        #region Comments

        /// <summary>A wrapper class for the Comments resource.</summary>
        public class Comments
        {




            /// <summary>Creates a new comment on a file.</summary>
            /// <param name="CommentBody">The body of the request.</param>
            /// <param name="FileId">The ID of the file.</param>
            public Google.Apis.Drive.v3.Data.Comment Create (Google.Apis.Drive.v3.Data.Comment CommentBody, string FileId)
            {

                return mainBase.comments.Create(CommentBody, FileId, gShellServiceAccount);
            }



            /// <summary>Deletes a comment.</summary>
            /// <param name="FileId">The ID of the file.</param>
            /// <param name="CommentId">The ID of the comment.</param>
            public void Delete (string FileId, string CommentId)
            {

                mainBase.comments.Delete(FileId, CommentId, gShellServiceAccount);
            }



            /// <summary>Gets a comment by ID.</summary>
            /// <param name="FileId">The ID of the file.</param>
            /// <param name="CommentId">The ID of the comment.</param>
            /// <param name="properties">The optional properties for this method.</param>
            public Google.Apis.Drive.v3.Data.Comment Get (string FileId, string CommentId, gDrive.Comments.CommentsGetProperties properties= null)
            {

                properties = properties ?? new gDrive.Comments.CommentsGetProperties();

                return mainBase.comments.Get(FileId, CommentId, properties, gShellServiceAccount);
            }



            /// <summary>Lists a file's comments.</summary>
            /// <param name="FileId">The ID of the file.</param>
            /// <param name="properties">The optional properties for this method.</param>

            public List<Google.Apis.Drive.v3.Data.CommentList> List(string FileId, gDrive.Comments.CommentsListProperties properties= null)
            {

                properties = properties ?? new gDrive.Comments.CommentsListProperties();


                return mainBase.comments.List(FileId, properties, gShellServiceAccount);
            }

            /// <summary>Updates a comment with patch semantics.</summary>
            /// <param name="CommentBody">The body of the request.</param>
            /// <param name="FileId">The ID of the file.</param>
            /// <param name="CommentId">The ID of the comment.</param>
            public Google.Apis.Drive.v3.Data.Comment Update (Google.Apis.Drive.v3.Data.Comment CommentBody, string FileId, string CommentId)
            {

                return mainBase.comments.Update(CommentBody, FileId, CommentId, gShellServiceAccount);
            }


        }
        #endregion



        #region Files

        /// <summary>A wrapper class for the Files resource.</summary>
        public class Files
        {




            /// <summary>Creates a copy of a file and applies any requested updates with patch semantics.</summary>
            /// <param name="FileBody">The body of the request.</param>
            /// <param name="FileId">The ID of the file.</param>
            /// <param name="properties">The optional properties for this method.</param>
            public Google.Apis.Drive.v3.Data.File Copy (Google.Apis.Drive.v3.Data.File FileBody, string FileId, gDrive.Files.FilesCopyProperties properties= null)
            {

                properties = properties ?? new gDrive.Files.FilesCopyProperties();

                return mainBase.files.Copy(FileBody, FileId, properties, gShellServiceAccount);
            }



            /// <summary>Creates a new file.</summary>
            /// <param name="FileBody">The body of the request.</param>
            /// <param name="properties">The optional properties for this method.</param>
            public Google.Apis.Drive.v3.Data.File Create (Google.Apis.Drive.v3.Data.File FileBody, gDrive.Files.FilesCreateProperties properties= null)
            {

                properties = properties ?? new gDrive.Files.FilesCreateProperties();

                return mainBase.files.Create(FileBody, properties, gShellServiceAccount);
            }


            /// <summary>3</summary>
            public void Create (Google.Apis.Drive.v3.Data.File FileBody, System.IO.Stream stream, string contentType, gDrive.Files.FilesCreateProperties properties= null)
            {

                properties = properties ?? new gDrive.Files.FilesCreateProperties();

                mainBase.files.Create(FileBody, stream, contentType, properties, gShellServiceAccount);
            }

            /// <summary>Permanently deletes a file owned by the user without moving it to the trash. If the target is a
            /// folder, all descendants owned by the user are also deleted.</summary>
            /// <param name="FileId">The ID of the file.</param>
            public void Delete (string FileId)
            {

                mainBase.files.Delete(FileId, gShellServiceAccount);
            }



            /// <summary>Permanently deletes all of the user's trashed files.</summary>
            public void EmptyTrash ()
            {

                mainBase.files.EmptyTrash(gShellServiceAccount);
            }



            /// <summary>Exports a Google Doc to the requested MIME type and returns the exported content.</summary>
            /// <param name="FileId">The ID of the file.</param>
            /// <param name="MimeType">The MIME type of the format
            /// requested for this export.</param>
            public void Export (string FileId, string MimeType)
            {

                mainBase.files.Export(FileId, MimeType, gShellServiceAccount);
            }



            /// <summary>Generates a set of file IDs which can be provided in create requests.</summary>
            /// <param name="properties">The optional properties for this method.</param>
            public Google.Apis.Drive.v3.Data.GeneratedIds GenerateIds (gDrive.Files.FilesGenerateIdsProperties properties= null)
            {

                properties = properties ?? new gDrive.Files.FilesGenerateIdsProperties();

                return mainBase.files.GenerateIds(properties, gShellServiceAccount);
            }



            /// <summary>Gets a file's metadata or content by ID.</summary>
            /// <param name="FileId">The ID of the file.</param>
            /// <param name="properties">The optional properties for this method.</param>
            public Google.Apis.Drive.v3.Data.File Get (string FileId, gDrive.Files.FilesGetProperties properties= null)
            {

                properties = properties ?? new gDrive.Files.FilesGetProperties();

                return mainBase.files.Get(FileId, properties, gShellServiceAccount);
            }



            /// <summary>Lists or searches files.</summary>
            /// <param name="properties">The optional properties for this method.</param>

            public List<Google.Apis.Drive.v3.Data.FileList> List(gDrive.Files.FilesListProperties properties= null)
            {

                properties = properties ?? new gDrive.Files.FilesListProperties();

                return mainBase.files.List(properties, gShellServiceAccount);
            }

            /// <summary>Updates a file's metadata and/or content with patch semantics.</summary>
            /// <param name="FileBody">The body of the request.</param>
            /// <param name="FileId">The ID of the file.</param>
            /// <param name="properties">The optional properties for this method.</param>
            public Google.Apis.Drive.v3.Data.File Update (Google.Apis.Drive.v3.Data.File FileBody, string FileId, gDrive.Files.FilesUpdateProperties properties= null)
            {

                properties = properties ?? new gDrive.Files.FilesUpdateProperties();

                return mainBase.files.Update(FileBody, FileId, properties, gShellServiceAccount);
            }


            /// <summary>3</summary>
            public void Update (Google.Apis.Drive.v3.Data.File FileBody, string fileId, System.IO.Stream stream, string contentType, gDrive.Files.FilesUpdateProperties properties= null)
            {

                properties = properties ?? new gDrive.Files.FilesUpdateProperties();

                mainBase.files.Update(FileBody, fileId, stream, contentType, properties, gShellServiceAccount);
            }

            /// <summary>Subscribes to changes to a file</summary>
            /// <param name="ChannelBody">The body of the request.</param>
            /// <param name="FileId">The ID of the file.</param>
            /// <param name="properties">The optional properties for this method.</param>
            public Google.Apis.Drive.v3.Data.Channel Watch (Google.Apis.Drive.v3.Data.Channel ChannelBody, string FileId, gDrive.Files.FilesWatchProperties properties= null)
            {

                properties = properties ?? new gDrive.Files.FilesWatchProperties();

                return mainBase.files.Watch(ChannelBody, FileId, properties, gShellServiceAccount);
            }


        }
        #endregion



        #region Permissions

        /// <summary>A wrapper class for the Permissions resource.</summary>
        public class Permissions
        {




            /// <summary>Creates a permission for a file.</summary>
            /// <param name="PermissionBody">The body of the request.</param>
            /// <param name="FileId">The ID of the file.</param>
            /// <param name="properties">The optional properties for this method.</param>
            public Google.Apis.Drive.v3.Data.Permission Create (Google.Apis.Drive.v3.Data.Permission PermissionBody, string FileId, gDrive.Permissions.PermissionsCreateProperties properties= null)
            {

                properties = properties ?? new gDrive.Permissions.PermissionsCreateProperties();

                return mainBase.permissions.Create(PermissionBody, FileId, properties, gShellServiceAccount);
            }



            /// <summary>Deletes a permission.</summary>
            /// <param name="FileId">The ID of the file.</param>
            /// <param name="PermissionId">The ID of the
            /// permission.</param>
            public void Delete (string FileId, string PermissionId)
            {

                mainBase.permissions.Delete(FileId, PermissionId, gShellServiceAccount);
            }



            /// <summary>Gets a permission by ID.</summary>
            /// <param name="FileId">The ID of the file.</param>
            /// <param name="PermissionId">The ID of the
            /// permission.</param>
            public Google.Apis.Drive.v3.Data.Permission Get (string FileId, string PermissionId)
            {

                return mainBase.permissions.Get(FileId, PermissionId, gShellServiceAccount);
            }



            /// <summary>Lists a file's permissions.</summary>
            /// <param name="FileId">The ID of the file.</param>
            public Google.Apis.Drive.v3.Data.PermissionList List (string FileId)
            {

                return mainBase.permissions.List(FileId, gShellServiceAccount);
            }



            /// <summary>Updates a permission with patch semantics.</summary>
            /// <param name="PermissionBody">The body of the request.</param>
            /// <param name="FileId">The ID of the file.</param>
            /// <param name="PermissionId">The ID of the
            /// permission.</param>
            /// <param name="properties">The optional properties for this method.</param>
            public Google.Apis.Drive.v3.Data.Permission Update (Google.Apis.Drive.v3.Data.Permission PermissionBody, string FileId, string PermissionId, gDrive.Permissions.PermissionsUpdateProperties properties= null)
            {

                properties = properties ?? new gDrive.Permissions.PermissionsUpdateProperties();

                return mainBase.permissions.Update(PermissionBody, FileId, PermissionId, properties, gShellServiceAccount);
            }


        }
        #endregion



        #region Replies

        /// <summary>A wrapper class for the Replies resource.</summary>
        public class Replies
        {




            /// <summary>Creates a new reply to a comment.</summary>
            /// <param name="ReplyBody">The body of the request.</param>
            /// <param name="FileId">The ID of the file.</param>
            /// <param name="CommentId">The ID of the comment.</param>
            public Google.Apis.Drive.v3.Data.Reply Create (Google.Apis.Drive.v3.Data.Reply ReplyBody, string FileId, string CommentId)
            {

                return mainBase.replies.Create(ReplyBody, FileId, CommentId, gShellServiceAccount);
            }



            /// <summary>Deletes a reply.</summary>
            /// <param name="FileId">The ID of the file.</param>
            /// <param name="CommentId">The ID of the
            /// comment.</param>
            /// <param name="ReplyId">The ID of the reply.</param>
            public void Delete (string FileId, string CommentId, string ReplyId)
            {

                mainBase.replies.Delete(FileId, CommentId, ReplyId, gShellServiceAccount);
            }



            /// <summary>Gets a reply by ID.</summary>
            /// <param name="FileId">The ID of the file.</param>
            /// <param name="CommentId">The ID of the
            /// comment.</param>
            /// <param name="ReplyId">The ID of the reply.</param>
            /// <param name="properties">The optional properties for this method.</param>
            public Google.Apis.Drive.v3.Data.Reply Get (string FileId, string CommentId, string ReplyId, gDrive.Replies.RepliesGetProperties properties= null)
            {

                properties = properties ?? new gDrive.Replies.RepliesGetProperties();

                return mainBase.replies.Get(FileId, CommentId, ReplyId, properties, gShellServiceAccount);
            }



            /// <summary>Lists a comment's replies.</summary>
            /// <param name="FileId">The ID of the file.</param>
            /// <param name="CommentId">The ID of the comment.</param>
            /// <param name="properties">The optional properties for this method.</param>

            public List<Google.Apis.Drive.v3.Data.ReplyList> List(string FileId, string CommentId, gDrive.Replies.RepliesListProperties properties= null)
            {

                properties = properties ?? new gDrive.Replies.RepliesListProperties();


                return mainBase.replies.List(FileId, CommentId, properties, gShellServiceAccount);
            }

            /// <summary>Updates a reply with patch semantics.</summary>
            /// <param name="ReplyBody">The body of the request.</param>
            /// <param name="FileId">The ID of the file.</param>
            /// <param name="CommentId">The ID of the
            /// comment.</param>
            /// <param name="ReplyId">The ID of the reply.</param>
            public Google.Apis.Drive.v3.Data.Reply Update (Google.Apis.Drive.v3.Data.Reply ReplyBody, string FileId, string CommentId, string ReplyId)
            {

                return mainBase.replies.Update(ReplyBody, FileId, CommentId, ReplyId, gShellServiceAccount);
            }


        }
        #endregion



        #region Revisions

        /// <summary>A wrapper class for the Revisions resource.</summary>
        public class Revisions
        {




            /// <summary>Permanently deletes a revision. This method is only applicable to files with binary content in
            /// Drive.</summary>
            /// <param name="FileId">The ID of the file.</param>
            /// <param name="RevisionId">The ID of the
            /// revision.</param>
            public void Delete (string FileId, string RevisionId)
            {

                mainBase.revisions.Delete(FileId, RevisionId, gShellServiceAccount);
            }



            /// <summary>Gets a revision's metadata or content by ID.</summary>
            /// <param name="FileId">The ID of the file.</param>
            /// <param name="RevisionId">The ID of the
            /// revision.</param>
            /// <param name="properties">The optional properties for this method.</param>
            public Google.Apis.Drive.v3.Data.Revision Get (string FileId, string RevisionId, gDrive.Revisions.RevisionsGetProperties properties= null)
            {

                properties = properties ?? new gDrive.Revisions.RevisionsGetProperties();

                return mainBase.revisions.Get(FileId, RevisionId, properties, gShellServiceAccount);
            }



            /// <summary>Lists a file's revisions.</summary>
            /// <param name="FileId">The ID of the file.</param>
            public Google.Apis.Drive.v3.Data.RevisionList List (string FileId)
            {

                return mainBase.revisions.List(FileId, gShellServiceAccount);
            }



            /// <summary>Updates a revision with patch semantics.</summary>
            /// <param name="RevisionBody">The body of the request.</param>
            /// <param name="FileId">The ID of the file.</param>
            /// <param name="RevisionId">The ID of the
            /// revision.</param>
            public Google.Apis.Drive.v3.Data.Revision Update (Google.Apis.Drive.v3.Data.Revision RevisionBody, string FileId, string RevisionId)
            {

                return mainBase.revisions.Update(RevisionBody, FileId, RevisionId, gShellServiceAccount);
            }


        }
        #endregion

        #endregion

    }
}



namespace gShell.dotNet
{
    using System;
    using System.Collections.Generic;

    using gShell.dotNet;
    using gShell.dotNet.Utilities.OAuth2;

    using v3 = Google.Apis.Drive.v3;
    using Data = Google.Apis.Drive.v3.Data;

    /// <summary>The dotNet gShell version of the drive api.</summary>
    public class Drive : ServiceWrapper<v3.DriveService>
    {

        protected override bool worksWithGmail { get { return true; } }

        /// <summary>Creates a new v3.Drive service.</summary>
        /// <param name="domain">The domain to which this service will be authenticated.</param>
        /// <param name="authInfo">The authenticated AuthInfo for this user and domain.</param>
        /// <param name="gShellServiceAccount">The optional email address the service account should impersonate.</param>

        protected override v3.DriveService CreateNewService(string domain, AuthenticatedUserInfo authInfo, string gShellServiceAccount = null)
        {
            return new v3.DriveService(OAuth2Base.GetInitializer(domain, authInfo, gShellServiceAccount));
        }

        /// <summary>Returns the api name and version in {name}:{version} format.</summary>
        public override string apiNameAndVersion { get { return "drive:v3"; } }


        /// <summary>Gets or sets the about resource class.</summary>
        public About about{ get; set; }

        /// <summary>Gets or sets the changes resource class.</summary>
        public Changes changes{ get; set; }

        /// <summary>Gets or sets the channels resource class.</summary>
        public Channels channels{ get; set; }

        /// <summary>Gets or sets the comments resource class.</summary>
        public Comments comments{ get; set; }

        /// <summary>Gets or sets the files resource class.</summary>
        public Files files{ get; set; }

        /// <summary>Gets or sets the permissions resource class.</summary>
        public Permissions permissions{ get; set; }

        /// <summary>Gets or sets the replies resource class.</summary>
        public Replies replies{ get; set; }

        /// <summary>Gets or sets the revisions resource class.</summary>
        public Revisions revisions{ get; set; }

        public Drive()
        {

            about = new About();
            changes = new Changes();
            channels = new Channels();
            comments = new Comments();
            files = new Files();
            permissions = new Permissions();
            replies = new Replies();
            revisions = new Revisions();
        }



        /// <summary>The "about" collection of methods.</summary>
        public class About
        {




            /// <summary>Gets information about the user, the user's Drive, and system capabilities.</summary>
            /// <param name="gShellServiceAccount">The optional email address the service account should impersonate.</param>
            public Google.Apis.Drive.v3.Data.About Get (string gShellServiceAccount = null)
            {
                return GetService(gShellServiceAccount).About.Get().Execute();
            }

        }

        /// <summary>The "changes" collection of methods.</summary>
        public class Changes
        {

            /// <summary>Optional parameters for the Changes List method.</summary>
            public class ChangesListProperties
            {
                /// <summary>Whether to include changes indicating that items have left the view of the changes list, for example by deletion or lost access.</summary>
                public System.Nullable<bool> IncludeRemoved = null;

                /// <summary>The maximum number of changes to return per page.</summary>
                public System.Nullable<int> PageSize = null;

                /// <summary>Whether to restrict the results to changes inside the My Drive hierarchy. This omits changes to files such as those in the Application Data folder or shared files which have not been added to My Drive.</summary>
                public System.Nullable<bool> RestrictToMyDrive = null;

                /// <summary>A comma-separated list of spaces to query within the user corpus. Supported values are 'drive', 'appDataFolder' and 'photos'.</summary>
                public string Spaces = null;
            }

            /// <summary>Optional parameters for the Changes Watch method.</summary>
            public class ChangesWatchProperties
            {
                /// <summary>Whether to include changes indicating that items have left the view of the changes list, for example by deletion or lost access.</summary>
                public System.Nullable<bool> IncludeRemoved = null;

                /// <summary>The maximum number of changes to return per page.</summary>
                public System.Nullable<int> PageSize = null;

                /// <summary>Whether to restrict the results to changes inside the My Drive hierarchy. This omits changes to files such as those in the Application Data folder or shared files which have not been added to My Drive.</summary>
                public System.Nullable<bool> RestrictToMyDrive = null;

                /// <summary>A comma-separated list of spaces to query within the user corpus. Supported values are 'drive', 'appDataFolder' and 'photos'.</summary>
                public string Spaces = null;
            }


            /// <summary>Gets the starting pageToken for listing future changes.</summary>
            /// <param name="gShellServiceAccount">The optional email address the service account should impersonate.</param>
            public Google.Apis.Drive.v3.Data.StartPageToken GetStartPageToken (string gShellServiceAccount = null)
            {
                return GetService(gShellServiceAccount).Changes.GetStartPageToken().Execute();
            }

            /// <summary>Lists changes for a user.</summary>
            /// <param name="PageToken">The token for continuing a previous list request on the next page. This should be set to the
            /// value of 'nextPageToken' from the previous response or to the response from the getStartPageToken
            /// method.</param>
            /// <param name="properties">The optional properties for this method.</param>
            /// <param name="gShellServiceAccount">The optional email address the service account should impersonate.</param>
            public Google.Apis.Drive.v3.Data.ChangeList List (string PageToken, ChangesListProperties properties= null, string gShellServiceAccount = null)
            {
                return GetService(gShellServiceAccount).Changes.List(PageToken).Execute();
            }

            /// <summary>Subscribes to changes for a user.</summary>
            /// <param name="ChannelBody">The body of the request.</param>
            /// <param name="PageToken">The token for continuing a previous list request on the next page. This should be set to the
            /// value of 'nextPageToken' from the previous response or to the response from the getStartPageToken
            /// method.</param>
            /// <param name="properties">The optional properties for this method.</param>
            /// <param name="gShellServiceAccount">The optional email address the service account should impersonate.</param>
            public Google.Apis.Drive.v3.Data.Channel Watch (Google.Apis.Drive.v3.Data.Channel ChannelBody, string PageToken, ChangesWatchProperties properties= null, string gShellServiceAccount = null)
            {
                return GetService(gShellServiceAccount).Changes.Watch(ChannelBody, PageToken).Execute();
            }

        }

        /// <summary>The "channels" collection of methods.</summary>
        public class Channels
        {




            /// <summary>Stop watching resources through this channel</summary>
            /// <param name="ChannelBody">The body of the request.</param>
            /// <param name="gShellServiceAccount">The optional email address the service account should impersonate.</param>
            public void Stop (Google.Apis.Drive.v3.Data.Channel ChannelBody, string gShellServiceAccount = null)
            {
                GetService(gShellServiceAccount).Channels.Stop(ChannelBody).Execute();
            }

        }

        /// <summary>The "comments" collection of methods.</summary>
        public class Comments
        {

            /// <summary>Optional parameters for the Comments Get method.</summary>
            public class CommentsGetProperties
            {
                /// <summary>Whether to return deleted comments. Deleted comments will not include their original content.</summary>
                public System.Nullable<bool> IncludeDeleted = null;
            }

            /// <summary>Optional parameters for the Comments List method.</summary>
            public class CommentsListProperties
            {
                /// <summary>Whether to include deleted comments. Deleted comments will not include their original content.</summary>
                public System.Nullable<bool> IncludeDeleted = null;

                /// <summary>The maximum number of comments to return per page.</summary>
                public System.Nullable<int> PageSize = null;

                /// <summary>The minimum value of 'modifiedTime' for the result comments (RFC 3339 date-time).</summary>
                public string StartModifiedTime = null;

                /// <summary>A delegate that is used to start a progress bar.</summary>
                public Action<string, string> StartProgressBar = null;

                /// <summary>A delegate that is used to update a progress bar.</summary>
                public Action<int, int, string, string> UpdateProgressBar = null;

                /// <summary>A counter for the total number of results to pull when iterating through paged results.</summary>
                public int TotalResults = 0;
            }


            /// <summary>Creates a new comment on a file.</summary>
            /// <param name="CommentBody">The body of the request.</param>
            /// <param name="FileId">The ID of the file.</param>
            /// <param name="gShellServiceAccount">The optional email address the service account should impersonate.</param>
            public Google.Apis.Drive.v3.Data.Comment Create (Google.Apis.Drive.v3.Data.Comment CommentBody, string FileId, string gShellServiceAccount = null)
            {
                return GetService(gShellServiceAccount).Comments.Create(CommentBody, FileId).Execute();
            }

            /// <summary>Deletes a comment.</summary>
            /// <param name="FileId">The ID of the file.</param>
            /// <param name="CommentId">The ID of the comment.</param>
            /// <param name="gShellServiceAccount">The optional email address the service account should impersonate.</param>
            public void Delete (string FileId, string CommentId, string gShellServiceAccount = null)
            {
                GetService(gShellServiceAccount).Comments.Delete(FileId, CommentId).Execute();
            }

            /// <summary>Gets a comment by ID.</summary>
            /// <param name="FileId">The ID of the file.</param>
            /// <param name="CommentId">The ID of the comment.</param>
            /// <param name="properties">The optional properties for this method.</param>
            /// <param name="gShellServiceAccount">The optional email address the service account should impersonate.</param>
            public Google.Apis.Drive.v3.Data.Comment Get (string FileId, string CommentId, CommentsGetProperties properties= null, string gShellServiceAccount = null)
            {
                return GetService(gShellServiceAccount).Comments.Get(FileId, CommentId).Execute();
            }

            /// <summary>Lists a file's comments.</summary>
            /// <param name="FileId">The ID of the file.</param>
            /// <param name="properties">The optional properties for this method.</param>
            /// <param name="gShellServiceAccount">The optional email address the service account should impersonate.</param>
            public List<Google.Apis.Drive.v3.Data.CommentList> List(
                string FileId, CommentsListProperties properties= null, string gShellServiceAccount = null)
            {
                var results = new List<Google.Apis.Drive.v3.Data.CommentList>();

                v3.CommentsResource.ListRequest request = GetService(gShellServiceAccount).Comments.List(FileId);

                if (properties != null)
                {
                    request.IncludeDeleted = properties.IncludeDeleted;
                    request.PageSize = properties.PageSize;
                    request.StartModifiedTime = properties.StartModifiedTime;

                }

                if (null != properties.StartProgressBar)
                {
                    properties.StartProgressBar("Gathering Comments",
                        string.Format("-Collecting Comments 1 to {0}", "unknown"));
                }

                Google.Apis.Drive.v3.Data.CommentList pagedResult = request.Execute();

                if (pagedResult != null)
                {
                    results.Add(pagedResult);

                    while (!string.IsNullOrWhiteSpace(pagedResult.NextPageToken) &&
                        pagedResult.NextPageToken != request.PageToken &&
                    (properties.TotalResults == 0 || results.Count < properties.TotalResults))
                    {
                        request.PageToken = pagedResult.NextPageToken;

                        if (null != properties.UpdateProgressBar)
                        {
                            properties.UpdateProgressBar(5, 10, "Gathering Comments",
                                    string.Format("-Collecting Comments {0} to {1}",
                                        (results.Count + 1).ToString(),
                                        "unknown"));
                        }
                        pagedResult = request.Execute();
                        results.Add(pagedResult);
                    }

                    if (null != properties.UpdateProgressBar)
                    {
                        properties.UpdateProgressBar(1, 2, "Gathering Comments",
                                string.Format("-Returning {0} results.", results.Count.ToString()));
                    }
                }

                return results;
            }

            /// <summary>Updates a comment with patch semantics.</summary>
            /// <param name="CommentBody">The body of the request.</param>
            /// <param name="FileId">The ID of the file.</param>
            /// <param name="CommentId">The ID of the comment.</param>
            /// <param name="gShellServiceAccount">The optional email address the service account should impersonate.</param>
            public Google.Apis.Drive.v3.Data.Comment Update (Google.Apis.Drive.v3.Data.Comment CommentBody, string FileId, string CommentId, string gShellServiceAccount = null)
            {
                return GetService(gShellServiceAccount).Comments.Update(CommentBody, FileId, CommentId).Execute();
            }

        }

        /// <summary>The "files" collection of methods.</summary>
        public class Files
        {

            /// <summary>Optional parameters for the Files Copy method.</summary>
            public class FilesCopyProperties
            {
                /// <summary>Whether to ignore the domain's default visibility settings for the created file. Domain administrators can choose to make all uploaded files visible to the domain by default; this parameter bypasses that behavior for the request. Permissions are still inherited from parent folders.</summary>
                public System.Nullable<bool> IgnoreDefaultVisibility = null;

                /// <summary>Whether to set the 'keepForever' field in the new head revision. This is only applicable to files with binary content in Drive.</summary>
                public System.Nullable<bool> KeepRevisionForever = null;

                /// <summary>A language hint for OCR processing during image import (ISO 639-1 code).</summary>
                public string OcrLanguage = null;
            }

            /// <summary>Optional parameters for the Files Create method.</summary>
            public class FilesCreateProperties
            {
                /// <summary>Whether to ignore the domain's default visibility settings for the created file. Domain administrators can choose to make all uploaded files visible to the domain by default; this parameter bypasses that behavior for the request. Permissions are still inherited from parent folders.</summary>
                public System.Nullable<bool> IgnoreDefaultVisibility = null;

                /// <summary>Whether to set the 'keepForever' field in the new head revision. This is only applicable to files with binary content in Drive.</summary>
                public System.Nullable<bool> KeepRevisionForever = null;

                /// <summary>A language hint for OCR processing during image import (ISO 639-1 code).</summary>
                public string OcrLanguage = null;

                /// <summary>Whether to use the uploaded content as indexable text.</summary>
                public System.Nullable<bool> UseContentAsIndexableText = null;
            }

            /// <summary>Optional parameters for the Files GenerateIds method.</summary>
            public class FilesGenerateIdsProperties
            {
                /// <summary>The number of IDs to return.</summary>
                public System.Nullable<int> Count = null;

                /// <summary>The space in which the IDs can be used to create new files. Supported values are 'drive' and 'appDataFolder'.</summary>
                public string Space = null;
            }

            /// <summary>Optional parameters for the Files Get method.</summary>
            public class FilesGetProperties
            {
                /// <summary>Whether the user is acknowledging the risk of downloading known malware or other abusive files. This is only applicable when alt=media.</summary>
                public System.Nullable<bool> AcknowledgeAbuse = null;
            }

            /// <summary>Optional parameters for the Files List method.</summary>
            public class FilesListProperties
            {
                /// <summary>The source of files to list.</summary>
                public v3.FilesResource.ListRequest.CorpusEnum?Corpus = null;

                /// <summary>A comma-separated list of sort keys. Valid keys are 'createdTime', 'folder', 'modifiedByMeTime', 'modifiedTime', 'name', 'quotaBytesUsed', 'recency', 'sharedWithMeTime', 'starred', and 'viewedByMeTime'. Each key sorts ascending by default, but may be reversed with the 'desc' modifier. Example usage: ?orderBy=folder,modifiedTime desc,name. Please note that there is a current limitation for users with approximately one million files in which the requested sort order is ignored.</summary>
                public string OrderBy = null;

                /// <summary>The maximum number of files to return per page.</summary>
                public System.Nullable<int> PageSize = null;

                /// <summary>A query for filtering the file results. See the "Search for Files" guide for supported syntax.</summary>
                public string Q = null;

                /// <summary>A comma-separated list of spaces to query within the corpus. Supported values are 'drive', 'appDataFolder' and 'photos'.</summary>
                public string Spaces = null;

                /// <summary>A delegate that is used to start a progress bar.</summary>
                public Action<string, string> StartProgressBar = null;

                /// <summary>A delegate that is used to update a progress bar.</summary>
                public Action<int, int, string, string> UpdateProgressBar = null;

                /// <summary>A counter for the total number of results to pull when iterating through paged results.</summary>
                public int TotalResults = 0;
            }

            /// <summary>Optional parameters for the Files Update method.</summary>
            public class FilesUpdateProperties
            {
                /// <summary>A comma-separated list of parent IDs to add.</summary>
                public string AddParents = null;

                /// <summary>Whether to set the 'keepForever' field in the new head revision. This is only applicable to files with binary content in Drive.</summary>
                public System.Nullable<bool> KeepRevisionForever = null;

                /// <summary>A language hint for OCR processing during image import (ISO 639-1 code).</summary>
                public string OcrLanguage = null;

                /// <summary>A comma-separated list of parent IDs to remove.</summary>
                public string RemoveParents = null;

                /// <summary>Whether to use the uploaded content as indexable text.</summary>
                public System.Nullable<bool> UseContentAsIndexableText = null;
            }

            /// <summary>Optional parameters for the Files Watch method.</summary>
            public class FilesWatchProperties
            {
                /// <summary>Whether the user is acknowledging the risk of downloading known malware or other abusive files. This is only applicable when alt=media.</summary>
                public System.Nullable<bool> AcknowledgeAbuse = null;
            }


            /// <summary>Creates a copy of a file and applies any requested updates with patch semantics.</summary>
            /// <param name="FileBody">The body of the request.</param>
            /// <param name="FileId">The ID of the file.</param>
            /// <param name="properties">The optional properties for this method.</param>
            /// <param name="gShellServiceAccount">The optional email address the service account should impersonate.</param>
            public Google.Apis.Drive.v3.Data.File Copy (Google.Apis.Drive.v3.Data.File FileBody, string FileId, FilesCopyProperties properties= null, string gShellServiceAccount = null)
            {
                return GetService(gShellServiceAccount).Files.Copy(FileBody, FileId).Execute();
            }

            /// <summary>Creates a new file.</summary>
            /// <param name="FileBody">The body of the request.</param>
            /// <param name="properties">The optional properties for this method.</param>
            /// <param name="gShellServiceAccount">The optional email address the service account should impersonate.</param>
            public Google.Apis.Drive.v3.Data.File Create (Google.Apis.Drive.v3.Data.File FileBody, FilesCreateProperties properties= null, string gShellServiceAccount = null)
            {
                return GetService(gShellServiceAccount).Files.Create(FileBody).Execute();
            }


            public void Create (Google.Apis.Drive.v3.Data.File FileBody, System.IO.Stream stream, string contentType, FilesCreateProperties properties= null, string gShellServiceAccount = null)
            {
                GetService(gShellServiceAccount).Files.Create(FileBody, stream, contentType).Upload();
            }

            /// <summary>Permanently deletes a file owned by the user without moving it to the trash. If the target is a
            /// folder, all descendants owned by the user are also deleted.</summary>
            /// <param name="FileId">The ID of the file.</param>
            /// <param name="gShellServiceAccount">The optional email address the service account should impersonate.</param>
            public void Delete (string FileId, string gShellServiceAccount = null)
            {
                GetService(gShellServiceAccount).Files.Delete(FileId).Execute();
            }

            /// <summary>Permanently deletes all of the user's trashed files.</summary>
            /// <param name="gShellServiceAccount">The optional email address the service account should impersonate.</param>
            public void EmptyTrash (string gShellServiceAccount = null)
            {
                GetService(gShellServiceAccount).Files.EmptyTrash().Execute();
            }

            /// <summary>Exports a Google Doc to the requested MIME type and returns the exported content.</summary>
            /// <param name="FileId">The ID of the file.</param>
            /// <param name="MimeType">The MIME type of the format
            /// requested for this export.</param>
            /// <param name="gShellServiceAccount">The optional email address the service account should impersonate.</param>
            public void Export (string FileId, string MimeType, string gShellServiceAccount = null)
            {
                GetService(gShellServiceAccount).Files.Export(FileId, MimeType).Execute();
            }

            /// <summary>Generates a set of file IDs which can be provided in create requests.</summary>
            /// <param name="properties">The optional properties for this method.</param>
            /// <param name="gShellServiceAccount">The optional email address the service account should impersonate.</param>
            public Google.Apis.Drive.v3.Data.GeneratedIds GenerateIds (FilesGenerateIdsProperties properties= null, string gShellServiceAccount = null)
            {
                return GetService(gShellServiceAccount).Files.GenerateIds().Execute();
            }

            /// <summary>Gets a file's metadata or content by ID.</summary>
            /// <param name="FileId">The ID of the file.</param>
            /// <param name="properties">The optional properties for this method.</param>
            /// <param name="gShellServiceAccount">The optional email address the service account should impersonate.</param>
            public Google.Apis.Drive.v3.Data.File Get (string FileId, FilesGetProperties properties= null, string gShellServiceAccount = null)
            {
                return GetService(gShellServiceAccount).Files.Get(FileId).Execute();
            }

            /// <summary>Lists or searches files.</summary>
            /// <param name="properties">The optional properties for this method.</param>
            /// <param name="gShellServiceAccount">The optional email address the service account should impersonate.</param>
            public List<Google.Apis.Drive.v3.Data.FileList> List(
                FilesListProperties properties= null, string gShellServiceAccount = null)
            {
                var results = new List<Google.Apis.Drive.v3.Data.FileList>();

                v3.FilesResource.ListRequest request = GetService(gShellServiceAccount).Files.List();

                if (properties != null)
                {
                    request.Corpus = properties.Corpus;
                    request.OrderBy = properties.OrderBy;
                    request.PageSize = properties.PageSize;
                    request.Q = properties.Q;
                    request.Spaces = properties.Spaces;
                }

                if (!properties.PageSize.HasValue) properties.PageSize = 100; //default value

                if (null != properties.StartProgressBar)
                {
                    properties.StartProgressBar("Gathering Files",
                        string.Format("-Collecting Files 1 to {0}", "unknown"));
                }

                Google.Apis.Drive.v3.Data.FileList pagedResult = request.Execute();

                if (pagedResult != null)
                {
                    results.Add(pagedResult);

                    while (!string.IsNullOrWhiteSpace(pagedResult.NextPageToken) &&
                        pagedResult.NextPageToken != request.PageToken &&
                    (properties.TotalResults == 0 || results.Count * properties.PageSize.Value < properties.TotalResults))
                    {
                        request.PageToken = pagedResult.NextPageToken;

                        if (null != properties.UpdateProgressBar)
                        {
                            properties.UpdateProgressBar(5, 10, "Gathering Files",
                                    string.Format("-Collecting Files {0} to {1}",
                                        (results.Count + 1).ToString(),
                                        "unknown"));
                        }
                        pagedResult = request.Execute();
                        results.Add(pagedResult);
                    }

                    if (null != properties.UpdateProgressBar)
                    {
                        properties.UpdateProgressBar(1, 2, "Gathering Files",
                                string.Format("-Returning {0} results.", results.Count.ToString()));
                    }
                }

                return results;
            }

            /// <summary>Updates a file's metadata and/or content with patch semantics.</summary>
            /// <param name="FileBody">The body of the request.</param>
            /// <param name="FileId">The ID of the file.</param>
            /// <param name="properties">The optional properties for this method.</param>
            /// <param name="gShellServiceAccount">The optional email address the service account should impersonate.</param>
            public Google.Apis.Drive.v3.Data.File Update (Google.Apis.Drive.v3.Data.File FileBody, string FileId, FilesUpdateProperties properties= null, string gShellServiceAccount = null)
            {
                return GetService(gShellServiceAccount).Files.Update(FileBody, FileId).Execute();
            }


            public void Update (Google.Apis.Drive.v3.Data.File FileBody, string fileId, System.IO.Stream stream, string contentType, FilesUpdateProperties properties= null, string gShellServiceAccount = null)
            {
                GetService(gShellServiceAccount).Files.Update(FileBody, fileId, stream, contentType).Upload();
            }

            /// <summary>Subscribes to changes to a file</summary>
            /// <param name="ChannelBody">The body of the request.</param>
            /// <param name="FileId">The ID of the file.</param>
            /// <param name="properties">The optional properties for this method.</param>
            /// <param name="gShellServiceAccount">The optional email address the service account should impersonate.</param>
            public Google.Apis.Drive.v3.Data.Channel Watch (Google.Apis.Drive.v3.Data.Channel ChannelBody, string FileId, FilesWatchProperties properties= null, string gShellServiceAccount = null)
            {
                return GetService(gShellServiceAccount).Files.Watch(ChannelBody, FileId).Execute();
            }

        }

        /// <summary>The "permissions" collection of methods.</summary>
        public class Permissions
        {

            /// <summary>Optional parameters for the Permissions Create method.</summary>
            public class PermissionsCreateProperties
            {
                /// <summary>A custom message to include in the notification email.</summary>
                public string EmailMessage = null;

                /// <summary>Whether to send a notification email when sharing to users or groups. This defaults to true for users and groups, and is not allowed for other requests. It must not be disabled for ownership transfers.</summary>
                public System.Nullable<bool> SendNotificationEmail = null;

                /// <summary>Whether to transfer ownership to the specified user and downgrade the current owner to a writer. This parameter is required as an acknowledgement of the side effect.</summary>
                public System.Nullable<bool> TransferOwnership = null;
            }

            /// <summary>Optional parameters for the Permissions Update method.</summary>
            public class PermissionsUpdateProperties
            {
                /// <summary>Whether to transfer ownership to the specified user and downgrade the current owner to a writer. This parameter is required as an acknowledgement of the side effect.</summary>
                public System.Nullable<bool> TransferOwnership = null;
            }


            /// <summary>Creates a permission for a file.</summary>
            /// <param name="PermissionBody">The body of the request.</param>
            /// <param name="FileId">The ID of the file.</param>
            /// <param name="properties">The optional properties for this method.</param>
            /// <param name="gShellServiceAccount">The optional email address the service account should impersonate.</param>
            public Google.Apis.Drive.v3.Data.Permission Create (Google.Apis.Drive.v3.Data.Permission PermissionBody, string FileId, PermissionsCreateProperties properties= null, string gShellServiceAccount = null)
            {
                return GetService(gShellServiceAccount).Permissions.Create(PermissionBody, FileId).Execute();
            }

            /// <summary>Deletes a permission.</summary>
            /// <param name="FileId">The ID of the file.</param>
            /// <param name="PermissionId">The ID of the
            /// permission.</param>
            /// <param name="gShellServiceAccount">The optional email address the service account should impersonate.</param>
            public void Delete (string FileId, string PermissionId, string gShellServiceAccount = null)
            {
                GetService(gShellServiceAccount).Permissions.Delete(FileId, PermissionId).Execute();
            }

            /// <summary>Gets a permission by ID.</summary>
            /// <param name="FileId">The ID of the file.</param>
            /// <param name="PermissionId">The ID of the
            /// permission.</param>
            /// <param name="gShellServiceAccount">The optional email address the service account should impersonate.</param>
            public Google.Apis.Drive.v3.Data.Permission Get (string FileId, string PermissionId, string gShellServiceAccount = null)
            {
                return GetService(gShellServiceAccount).Permissions.Get(FileId, PermissionId).Execute();
            }

            /// <summary>Lists a file's permissions.</summary>
            /// <param name="FileId">The ID of the file.</param>
            /// <param name="gShellServiceAccount">The optional email address the service account should impersonate.</param>
            public Google.Apis.Drive.v3.Data.PermissionList List (string FileId, string gShellServiceAccount = null)
            {
                return GetService(gShellServiceAccount).Permissions.List(FileId).Execute();
            }

            /// <summary>Updates a permission with patch semantics.</summary>
            /// <param name="PermissionBody">The body of the request.</param>
            /// <param name="FileId">The ID of the file.</param>
            /// <param name="PermissionId">The ID of the
            /// permission.</param>
            /// <param name="properties">The optional properties for this method.</param>
            /// <param name="gShellServiceAccount">The optional email address the service account should impersonate.</param>
            public Google.Apis.Drive.v3.Data.Permission Update (Google.Apis.Drive.v3.Data.Permission PermissionBody, string FileId, string PermissionId, PermissionsUpdateProperties properties= null, string gShellServiceAccount = null)
            {
                return GetService(gShellServiceAccount).Permissions.Update(PermissionBody, FileId, PermissionId).Execute();
            }

        }

        /// <summary>The "replies" collection of methods.</summary>
        public class Replies
        {

            /// <summary>Optional parameters for the Replies Get method.</summary>
            public class RepliesGetProperties
            {
                /// <summary>Whether to return deleted replies. Deleted replies will not include their original content.</summary>
                public System.Nullable<bool> IncludeDeleted = null;
            }

            /// <summary>Optional parameters for the Replies List method.</summary>
            public class RepliesListProperties
            {
                /// <summary>Whether to include deleted replies. Deleted replies will not include their original content.</summary>
                public System.Nullable<bool> IncludeDeleted = null;

                /// <summary>The maximum number of replies to return per page.</summary>
                public System.Nullable<int> PageSize = null;

                /// <summary>A delegate that is used to start a progress bar.</summary>
                public Action<string, string> StartProgressBar = null;

                /// <summary>A delegate that is used to update a progress bar.</summary>
                public Action<int, int, string, string> UpdateProgressBar = null;

                /// <summary>A counter for the total number of results to pull when iterating through paged results.</summary>
                public int TotalResults = 0;
            }


            /// <summary>Creates a new reply to a comment.</summary>
            /// <param name="ReplyBody">The body of the request.</param>
            /// <param name="FileId">The ID of the file.</param>
            /// <param name="CommentId">The ID of the comment.</param>
            /// <param name="gShellServiceAccount">The optional email address the service account should impersonate.</param>
            public Google.Apis.Drive.v3.Data.Reply Create (Google.Apis.Drive.v3.Data.Reply ReplyBody, string FileId, string CommentId, string gShellServiceAccount = null)
            {
                return GetService(gShellServiceAccount).Replies.Create(ReplyBody, FileId, CommentId).Execute();
            }

            /// <summary>Deletes a reply.</summary>
            /// <param name="FileId">The ID of the file.</param>
            /// <param name="CommentId">The ID of the
            /// comment.</param>
            /// <param name="ReplyId">The ID of the reply.</param>
            /// <param name="gShellServiceAccount">The optional email address the service account should impersonate.</param>
            public void Delete (string FileId, string CommentId, string ReplyId, string gShellServiceAccount = null)
            {
                GetService(gShellServiceAccount).Replies.Delete(FileId, CommentId, ReplyId).Execute();
            }

            /// <summary>Gets a reply by ID.</summary>
            /// <param name="FileId">The ID of the file.</param>
            /// <param name="CommentId">The ID of the
            /// comment.</param>
            /// <param name="ReplyId">The ID of the reply.</param>
            /// <param name="properties">The optional properties for this method.</param>
            /// <param name="gShellServiceAccount">The optional email address the service account should impersonate.</param>
            public Google.Apis.Drive.v3.Data.Reply Get (string FileId, string CommentId, string ReplyId, RepliesGetProperties properties= null, string gShellServiceAccount = null)
            {
                return GetService(gShellServiceAccount).Replies.Get(FileId, CommentId, ReplyId).Execute();
            }

            /// <summary>Lists a comment's replies.</summary>
            /// <param name="FileId">The ID of the file.</param>
            /// <param name="CommentId">The ID of the comment.</param>
            /// <param name="properties">The optional properties for this method.</param>
            /// <param name="gShellServiceAccount">The optional email address the service account should impersonate.</param>
            public List<Google.Apis.Drive.v3.Data.ReplyList> List(
                string FileId, string CommentId, RepliesListProperties properties= null, string gShellServiceAccount = null)
            {
                var results = new List<Google.Apis.Drive.v3.Data.ReplyList>();

                v3.RepliesResource.ListRequest request = GetService(gShellServiceAccount).Replies.List(FileId, CommentId);

                if (properties != null)
                {
                    request.IncludeDeleted = properties.IncludeDeleted;
                    request.PageSize = properties.PageSize;

                }

                if (null != properties.StartProgressBar)
                {
                    properties.StartProgressBar("Gathering Replies",
                        string.Format("-Collecting Replies 1 to {0}", "unknown"));
                }

                Google.Apis.Drive.v3.Data.ReplyList pagedResult = request.Execute();

                if (pagedResult != null)
                {
                    results.Add(pagedResult);

                    while (!string.IsNullOrWhiteSpace(pagedResult.NextPageToken) &&
                        pagedResult.NextPageToken != request.PageToken &&
                    (properties.TotalResults == 0 || results.Count < properties.TotalResults))
                    {
                        request.PageToken = pagedResult.NextPageToken;

                        if (null != properties.UpdateProgressBar)
                        {
                            properties.UpdateProgressBar(5, 10, "Gathering Replies",
                                    string.Format("-Collecting Replies {0} to {1}",
                                        (results.Count + 1).ToString(),
                                        "unknown"));
                        }
                        pagedResult = request.Execute();
                        results.Add(pagedResult);
                    }

                    if (null != properties.UpdateProgressBar)
                    {
                        properties.UpdateProgressBar(1, 2, "Gathering Replies",
                                string.Format("-Returning {0} results.", results.Count.ToString()));
                    }
                }

                return results;
            }

            /// <summary>Updates a reply with patch semantics.</summary>
            /// <param name="ReplyBody">The body of the request.</param>
            /// <param name="FileId">The ID of the file.</param>
            /// <param name="CommentId">The ID of the
            /// comment.</param>
            /// <param name="ReplyId">The ID of the reply.</param>
            /// <param name="gShellServiceAccount">The optional email address the service account should impersonate.</param>
            public Google.Apis.Drive.v3.Data.Reply Update (Google.Apis.Drive.v3.Data.Reply ReplyBody, string FileId, string CommentId, string ReplyId, string gShellServiceAccount = null)
            {
                return GetService(gShellServiceAccount).Replies.Update(ReplyBody, FileId, CommentId, ReplyId).Execute();
            }

        }

        /// <summary>The "revisions" collection of methods.</summary>
        public class Revisions
        {

            /// <summary>Optional parameters for the Revisions Get method.</summary>
            public class RevisionsGetProperties
            {
                /// <summary>Whether the user is acknowledging the risk of downloading known malware or other abusive files. This is only applicable when alt=media.</summary>
                public System.Nullable<bool> AcknowledgeAbuse = null;
            }


            /// <summary>Permanently deletes a revision. This method is only applicable to files with binary content in
            /// Drive.</summary>
            /// <param name="FileId">The ID of the file.</param>
            /// <param name="RevisionId">The ID of the
            /// revision.</param>
            /// <param name="gShellServiceAccount">The optional email address the service account should impersonate.</param>
            public void Delete (string FileId, string RevisionId, string gShellServiceAccount = null)
            {
                GetService(gShellServiceAccount).Revisions.Delete(FileId, RevisionId).Execute();
            }

            /// <summary>Gets a revision's metadata or content by ID.</summary>
            /// <param name="FileId">The ID of the file.</param>
            /// <param name="RevisionId">The ID of the
            /// revision.</param>
            /// <param name="properties">The optional properties for this method.</param>
            /// <param name="gShellServiceAccount">The optional email address the service account should impersonate.</param>
            public Google.Apis.Drive.v3.Data.Revision Get (string FileId, string RevisionId, RevisionsGetProperties properties= null, string gShellServiceAccount = null)
            {
                return GetService(gShellServiceAccount).Revisions.Get(FileId, RevisionId).Execute();
            }

            /// <summary>Lists a file's revisions.</summary>
            /// <param name="FileId">The ID of the file.</param>
            /// <param name="gShellServiceAccount">The optional email address the service account should impersonate.</param>
            public Google.Apis.Drive.v3.Data.RevisionList List (string FileId, string gShellServiceAccount = null)
            {
                return GetService(gShellServiceAccount).Revisions.List(FileId).Execute();
            }

            /// <summary>Updates a revision with patch semantics.</summary>
            /// <param name="RevisionBody">The body of the request.</param>
            /// <param name="FileId">The ID of the file.</param>
            /// <param name="RevisionId">The ID of the
            /// revision.</param>
            /// <param name="gShellServiceAccount">The optional email address the service account should impersonate.</param>
            public Google.Apis.Drive.v3.Data.Revision Update (Google.Apis.Drive.v3.Data.Revision RevisionBody, string FileId, string RevisionId, string gShellServiceAccount = null)
            {
                return GetService(gShellServiceAccount).Revisions.Update(RevisionBody, FileId, RevisionId).Execute();
            }

        }

    }
}