// gShell is licensed under the GNU GENERAL PUBLIC LICENSE, Version 3
//
// http://www.gnu.org/licenses/gpl-3.0.en.html
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//
// gShell is based upon https://github.com/google/google-api-dotnet-client, which is licensed under the Apache 2.0
// license: https://github.com/google/google-api-dotnet-client/blob/master/LICENSE
//
// gShell is reliant upon the Google Apis. Please see the specific API pages for specific licensing information.

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a fork of google-apis-code-generator:
//       https://github.com/squid808/apis-client-generator
//
//     How neat is that? Pretty neat.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gShell.Cmdlets.Discovery{

    using System;
    using System.Collections.Generic;
    using System.Management.Automation;

    using Google.Apis.Auth.OAuth2;
    using Google.Apis.Services;
    using v1 = Google.Apis.Discovery.v1;
    using Data = Google.Apis.Discovery.v1.Data;

    using gShell.dotNet.Utilities;
    using gShell.dotNet.Utilities.OAuth2;
    using gDiscovery = gShell.dotNet.Discovery;

    /// <summary>
    /// A PowerShell-ready wrapper for the Discovery api, as well as the resources and methods therein.
    /// </summary>
    public abstract class DiscoveryBase : OAuth2CmdletBase
    {

        #region Properties

        /// <summary>
        /// <para type="description">The domain against which this cmdlet should run.</para>
        /// </summary>
        [Parameter(Mandatory = false)]
        [ValidateNotNullOrEmpty]
        public string Domain { get; set; }

        /// <summary>The gShell dotNet class wrapper base.</summary>
        protected static gDiscovery mainBase { get; set; }


        /// <summary>An instance of the Apis gShell dotNet resource.</summary>
        public Apis apis { get; set; }

        /// <summary>Returns the api name and version in {name}:{version} format.</summary>
        protected override string apiNameAndVersion { get { return mainBase.apiNameAndVersion; } }

        /// <summary>Gets or sets the email account the gShell Service Account should impersonate.</summary>
        protected static string gShellServiceAccount { get; set; }
        #endregion

        #region Constructors
        protected DiscoveryBase()
        {
            mainBase = new gDiscovery();

            apis = new Apis();
        }
        #endregion

        #region PowerShell Methods
        /// <summary>The gShell base implementation of the PowerShell BeginProcessing method.</summary>
        /// <remarks>If a service account needs to be identified, it should be in a child class that overrides
        /// and calls this method.</remarks>
        protected override void BeginProcessing()
        {
            var secrets = CheckForClientSecrets();
            if (secrets != null)
            {
                IEnumerable<string> scopes = EnsureScopesExist(Domain);
                Domain = mainBase.BuildService(Authenticate(scopes, secrets, Domain), gShellServiceAccount).domain;

                GWriteProgress = new gWriteProgress(WriteProgress);
            }
            else
            {
                WriteError(new ErrorRecord(null, (new Exception(
                    "Client Secrets must be set before running cmdlets. Run 'Get-Help "
                    + "Set-gShellClientSecrets -online' for more information."))));
            }
        }

        /// <summary>The gShell base implementation of the PowerShell EndProcessing method.</summary>
        /// <remarks>We need to reset the service account after every Cmdlet call to prevent the next
        /// Cmdlet from inheriting it as well.</remarks>
        protected override void EndProcessing()
        {
            gShellServiceAccount = string.Empty;
        }

        /// <summary>The gShell base implementation of the PowerShell StopProcessing method.</summary>
        /// <remarks>We need to reset the service account after every Cmdlet call to prevent the next
        /// Cmdlet from inheriting it as well.</remarks>
        protected override void StopProcessing()
        {
            gShellServiceAccount = string.Empty;
        }
        #endregion

        #region Authentication & Processing
        /// <summary>Ensure the user, domain and client secret combination work with an authenticated user.</summary>
        /// <param name="Scopes">The scopes that need to be passed through to the user authentication to Google.</param>
        /// <param name="Secrets">The client secrets.`</param>
        /// <param name="Domain">The domain for which this authentication is intended.</param>
        /// <returns>The AuthenticatedUserInfo for the authenticated user.</returns>
        protected override AuthenticatedUserInfo Authenticate(IEnumerable<string> Scopes, ClientSecrets Secrets, string Domain = null)
        {
            return mainBase.Authenticate(apiNameAndVersion, Scopes, Secrets, Domain);
        }
        #endregion

        #region Wrapped Methods



        #region Apis

        /// <summary>A wrapper class for the Apis resource.</summary>
        public class Apis
        {




            /// <summary>Retrieve the description of a particular version of an api.</summary>
            /// <param name="Api">The name of the API.</param>
            /// <param name="Version">The version of the API.</param>
            public Google.Apis.Discovery.v1.Data.RestDescription GetRest (string Api, string Version)
            {

                return mainBase.apis.GetRest(Api, Version, gShellServiceAccount);
            }



            /// <summary>Retrieve the list of APIs supported at this endpoint.</summary>
            /// <param name="properties">The optional properties for this method.</param>
            public Google.Apis.Discovery.v1.Data.DirectoryList List (gDiscovery.Apis.ApisListProperties properties= null)
            {

                properties = properties ?? new gDiscovery.Apis.ApisListProperties();

                return mainBase.apis.List(properties, gShellServiceAccount);
            }


        }
        #endregion

        #endregion

    }
}



namespace gShell.dotNet
{
    using System;
    using System.Collections.Generic;

    using gShell.dotNet;
    using gShell.dotNet.Utilities.OAuth2;

    using v1 = Google.Apis.Discovery.v1;
    using Data = Google.Apis.Discovery.v1.Data;

    /// <summary>The dotNet gShell version of the discovery api.</summary>
    public class Discovery : ServiceWrapper<v1.DiscoveryService>
    {

        protected override bool worksWithGmail { get { return true; } }

        /// <summary>Creates a new v1.Discovery service.</summary>
        /// <param name="domain">The domain to which this service will be authenticated.</param>
        /// <param name="authInfo">The authenticated AuthInfo for this user and domain.</param>
        /// <param name="gShellServiceAccount">The optional email address the service account should impersonate.</param>

        protected override v1.DiscoveryService CreateNewService(string domain, AuthenticatedUserInfo authInfo, string gShellServiceAccount = null)
        {
            return new v1.DiscoveryService(OAuth2Base.GetInitializer(domain, authInfo, gShellServiceAccount));
        }

        /// <summary>Returns the api name and version in {name}:{version} format.</summary>
        public override string apiNameAndVersion { get { return "discovery:v1"; } }


        /// <summary>Gets or sets the apis resource class.</summary>
        public Apis apis{ get; set; }

        public Discovery()
        {

            apis = new Apis();
        }



        /// <summary>The "apis" collection of methods.</summary>
        public class Apis
        {

            /// <summary>Optional parameters for the Apis List method.</summary>
            public class ApisListProperties
            {
                /// <summary>Only include APIs with the given name.</summary>
                public string Name = null;

                /// <summary>Return only the preferred version of an API.</summary>
                public System.Nullable<bool> Preferred = null;
            }


            /// <summary>Retrieve the description of a particular version of an api.</summary>
            /// <param name="Api">The name of the API.</param>
            /// <param name="Version">The version of the API.</param>
            /// <param name="gShellServiceAccount">The optional email address the service account should impersonate.</param>
            public Google.Apis.Discovery.v1.Data.RestDescription GetRest (string Api, string Version, string gShellServiceAccount = null)
            {
                return GetService(gShellServiceAccount).Apis.GetRest(Api, Version).Execute();
            }

            /// <summary>Retrieve the list of APIs supported at this endpoint.</summary>
            /// <param name="properties">The optional properties for this method.</param>
            /// <param name="gShellServiceAccount">The optional email address the service account should impersonate.</param>
            public Google.Apis.Discovery.v1.Data.DirectoryList List (ApisListProperties properties= null, string gShellServiceAccount = null)
            {
                return GetService(gShellServiceAccount).Apis.List().Execute();
            }

        }

    }
}